[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown --workspace --exclude proofkit-integration-tests"
wasm-debug = "build --lib --target wasm32-unknown-unknown --workspace --exclude proofkit-integration-tests"
